services:


  nginx:
    image: nginx
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - "${Nginx_Config_Dir}:/etc/nginx/conf.d"
      - files:/var/www/files:ro
    depends_on:
      - web_api
    networks:
      - app-network
  #      - dehydrated
  #
  #  dehydrated:
  #    image: linuxserver/dehydrated
  #    container_name: dehydrated
  #    environment:
  #      - DEHYDRATED_CHALLENGE=http-01
  #      - DEHYDRATED_DOMAIN=fashion-face.ai
  #      - DEHYDRATED_EMAIL=your-email@example.com
  #    volumes:
  #      - "${Dehydrated_Config_Dir}:/config"
  #      - ./nginx/www:/www # pointed from nginx.cert at location /.well-known/acme-challenge/
  #    command: ["--cron", "--hook", "/config/hook.sh"]
  #    restart: unless-stopped


  web_api:
    image: web_api
    container_name: web_api
    hostname: web_api
    build:
      context: .
      dockerfile: FashionFace.Executable.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$Environment
      - Database__ConnectionString=Host=${Postgres_Host};Port=${Postgres_Port};Database=${Postgres_Db};Username=${Postgres_User};Password=${Postgres_Password};Include Error Detail=true;
      - NanoBanana__ApiKey=$NanoBanana_ApiKey
      - Jwt__Issuer=$Jwt_Issuer
      - Jwt__Audience=$Jwt_Audience
      - Jwt__Secret=$Jwt_Secret
      - Jwt__AccessTokenExpiryMinutes=$Jwt_AccessTokenExpiryMinutes
      - Jwt__RefreshTokenExpiryDays=$Jwt_RefreshTokenExpiryDays
      - RabbitMq__Host=$RabbitMq_Host
      - RabbitMq__VHost=$RabbitMq_VHost
      - RabbitMq__Port=$RabbitMq_Port
      - RabbitMq__UserName=$RabbitMq_UserName
      - RabbitMq__Password=$RabbitMq_Password
      - Redis__Configuration=$Redis_Configuration
      - Redis__InstanceName=$Redis_InstanceName
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - "${Files_Dir}:/app/files:rw"
      - "${Web_Api_Log_Dir}:/app/logs:rw"
      - files:/app/files/media:ro
    depends_on:
      postgres_migration:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
      redis_stack:
        condition: service_started
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: unless-stopped
    networks:
      - app-network


  hubs:
    image: hubs
    container_name: hubs
    hostname: hubs
    build:
      context: .
      dockerfile: FashionFace.Executable.Hubs/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$Environment
      - Database__ConnectionString=Host=${Postgres_Host};Port=${Postgres_Port};Database=${Postgres_Db};Username=${Postgres_User};Password=${Postgres_Password};Include Error Detail=true;
      - NanoBanana__ApiKey=$NanoBanana_ApiKey
      - Jwt__Issuer=$Jwt_Issuer
      - Jwt__Audience=$Jwt_Audience
      - Jwt__Secret=$Jwt_Secret
      - Jwt__AccessTokenExpiryMinutes=$Jwt_AccessTokenExpiryMinutes
      - Jwt__RefreshTokenExpiryDays=$Jwt_RefreshTokenExpiryDays
      - RabbitMq__Host=$RabbitMq_Host
      - RabbitMq__VHost=$RabbitMq_VHost
      - RabbitMq__Port=$RabbitMq_Port
      - RabbitMq__UserName=$RabbitMq_UserName
      - RabbitMq__Password=$RabbitMq_Password
      - Redis__Configuration=$Redis_Configuration
      - Redis__InstanceName=$Redis_InstanceName
    ports:
      - "8090:8090"
    expose:
      - 8090
    volumes:
      - "${Hubs_Log_Dir}:/app/logs:rw"
    depends_on:
      postgres_migration:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
      redis_stack:
        condition: service_started
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: unless-stopped
    networks:
      - app-network


  user_event_worker:
    image: user_event_worker
    container_name: user_event_worker
    hostname: user_event_worker
    build:
      context: .
      dockerfile: FashionFace.Executable.Worker.UserEvents/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$Environment
      - Database__ConnectionString=Host=${Postgres_Host};Port=${Postgres_Port};Database=${Postgres_Db};Username=${Postgres_User};Password=${Postgres_Password};Include Error Detail=true;
      - RabbitMq__Host=$RabbitMq_Host
      - RabbitMq__VHost=$RabbitMq_VHost
      - RabbitMq__Port=$RabbitMq_Port
      - RabbitMq__UserName=$RabbitMq_UserName
      - RabbitMq__Password=$RabbitMq_Password
      - Redis__Configuration=$Redis_Configuration
      - Redis__InstanceName=$Redis_InstanceName
    depends_on:
      postgres_migration:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
      redis_stack:
        condition: service_started
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: unless-stopped
    networks:
      - app-network


  postgres_migration:
    image: postgres_migration
    container_name: postgres_migration
    build:
      context: .
      dockerfile: FashionFace.Executable.Console.Migration/Dockerfile
    environment:
      - Database__ConnectionString=Host=postgres;Port=${Postgres_Port};Database=${Postgres_Db};Username=${Postgres_User};Password=${Postgres_Password};Include Error Detail=true;
    volumes:
      - "${Files_Dir}:/app/files:rw"
      - "${Postgres_Migration_Log_Dir}:/app/logs:rw"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: no
    networks:
      - app-network

  postgres:
    image: postgres:18
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=$Postgres_Db
      - POSTGRES_USER=$Postgres_User
      - POSTGRES_PASSWORD=$Postgres_Password
      - TZ=UTC
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $Postgres_User -d $Postgres_Db" ]
      interval: 10s
      timeout: 10s
      retries: 15
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: unless-stopped
    networks:
      - app-network


  rabbitmq:
    image: rabbitmq:4.2.1
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RabbitMq_UserName
      - RABBITMQ_DEFAULT_PASS=$RabbitMq_Password
      - TZ=UTC
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    volumes:
      - rabbitmq_volume:/etc/rabbitmq/
      - "${Rabbitmq_Log_Dir}:/var/log/rabbitmq:rw"
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: unless-stopped
    networks:
      - app-network


  redis_stack:
    image: redis/redis-stack:7.4.0-v8
    container_name: redis_stack
    environment:
      - TZ=UTC
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis_volume:/data
      - "${Redis_Stack_Log_Dir}:/app/logs:rw"
    command: redis-server --logfile /app/logs/redis.log
    logging:
      options:
        max-size: $Docker_Log_Size
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


volumes:
  postgres_volume:
  rabbitmq_volume:
  redis_volume:
  files: